---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oathkeeper-maester
  labels:
    app.kubernetes.io/name: maester
    app.kubernetes.io/instance: oathkeeper
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: oathkeeper-maester
      app.kubernetes.io/instance: oathkeeper
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: oathkeeper-maester
        app.kubernetes.io/instance: oathkeeper
    spec:
      automountServiceAccountToken: true
      serviceAccountName: oathkeeper-maester
      containers:
        - name: maester
          image: "oryd/oathkeeper-maester:v0.1.10-amd64"
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --metrics-addr=0.0.0.0:8080
            - controller
            - --rulesConfigmapName=oathkeeper-rules
            - --rulesConfigmapNamespace=ory
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seLinuxOptions:
              level: s0:c123,c456
            seccompProfile:
              type: RuntimeDefault
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups: []
        sysctls: []
      terminationGracePeriodSeconds: 10
      nodeSelector:
