---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kratos-self-service-ui-node
spec:
  dependsOn:
    - name: linkerd
    - name: vault
    - name: ory-bootstrap
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kube-apisix-linkerd-ory-kustomize
  path: ./apps/kratos-self-service-ui-node
