---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trust-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: trust-manager
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 12h
