---
apiVersion: v1
kind: Service
metadata:
  name: http-dump
  labels:
    app.kubernetes.io/name: http-dump
    app.kubernetes.io/instance: http-dump
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: http-dump
    app.kubernetes.io/instance: http-dump
