apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apisix
spec:
  interval: 50m
  targetNamespace: apisix
  releaseName: apisix
  chart:
    spec:
      chart: apisix
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: apisix
      interval: 65m
  # https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml
  values:
    podAnnotations:
      linkerd.io/inject: enabled
    service:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
    dashboard:
      enabled: true
      podAnnotations:
        linkerd.io/inject: enabled
    ingress-controller:
      enabled: true
      podAnnotations:
        linkerd.io/inject: enabled
      config:
        apisix:
          serviceNamespace: apisix
          serviceName: apisix-admin
    etcd:
      podAnnotations:
        linkerd.io/inject: enabled
