apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
spec:
  interval: 50m
  chart:
    spec:
      chart: vault
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: vault
      interval: 65m
  # https://github.com/hashicorp/vault-helm/blob/main/values.yaml
  values:
    ui:
      enabled: true
    injector:
      enabled: false
