apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - ingress-class.yaml
  - rbac.yaml
  - service-account.yaml
  - service-apisix.yaml
  - service.yaml
