---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-linkerd-issuer
spec:
  vault:
    path: pki_linkerd/root/sign-intermediate
    server: http://vault.vault.svc.cluster.local:8200
    auth:
      kubernetes:
        role: vault-linkerd-issuer
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: cert-manager
