---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos-selfservice-ui-node
  namespace: ory
  labels:
    app.kubernetes.io/name: kratos-selfservice-ui-node
    app.kubernetes.io/instance: kratos-selfservice-ui-node
  annotations:
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: kratos-selfservice-ui-node
      app.kubernetes.io/instance: kratos-selfservice-ui-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kratos-selfservice-ui-node
        app.kubernetes.io/instance: kratos-selfservice-ui-node
      annotations:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: kratos-selfservice-ui-node
          image: "oryd/kratos-selfservice-ui-node:v0.13.0-21"
          imagePullPolicy: IfNotPresent
          env:
            - name: KRATOS_PUBLIC_URL
              value: "http://kratos-public.ory.svc.cluster.local:4433"
            - name: KRATOS_BROWSER_URL
              value: "http://identity.127.0.0.1.sslip.io/kratos"
            - name: KRATOS_ADMIN_URL
              value: "http://kratos-admins.ory.svc.cluster.local:4434/"
            - name: COOKIE_SECRET
              value: "change-me"
            - name: CSRF_COOKIE_NAME
              value: "change-me"
            - name: CSRF_COOKIE_SECRET
              value: "change-me"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/alive
              port: http
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 10000
            runAsNonRoot: true
            runAsUser: 10000
            seLinuxOptions:
              level: s0:c123,c456
            seccompProfile:
              type: RuntimeDefault
      securityContext:
        fsGroup: 10000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 10000
        runAsNonRoot: true
        runAsUser: 10000
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups: []
        sysctls: []
