---
apiVersion: v1
kind: Service
metadata:
  name: kratos-selfservice-ui-node
  labels:
    app.kubernetes.io/name: kratos-selfservice-ui-node
    app.kubernetes.io/instance: kratos-selfservice-ui-node
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kratos-selfservice-ui-node
    app.kubernetes.io/instance: kratos-selfservice-ui-node
