---
# Source: apisix/charts/etcd/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: apisix-etcd
  namespace: "apisix"
  labels:
    app.kubernetes.io/name: etcd
    helm.sh/chart: etcd-8.7.7
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/managed-by: Helm
spec:
  minAvailable: 51%
  selector:
    matchLabels:
      app.kubernetes.io/name: etcd
      app.kubernetes.io/instance: apisix
