---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: kratos-selfservice-ui-node
spec:
  http:
    - name: kratos-selfservice-ui-node
      match:
        hosts:
          - auth.127.0.0.1.sslip.io
        paths:
          - "/*"
      backends:
        - serviceName: kratos-selfservice-ui-node
          servicePort: 3000
