apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-role-binding.yaml
  - config-map.yaml
  - namespace.yaml
  - service-account.yaml
  - service.yaml
  - stateful-set.yaml
