version: v0.13.0

dsn: memory

serve:
  admin:
    port: 4434
  public:
    port: 4433

selfservice:
  default_browser_return_url: http://auth.127.0.0.1.sslip.io/

log:
  level: info
  format: json
  leak_sensitive_values: false

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

cookies:
  domain: 127.0.0.1.sslip.io
  same_site: Lax

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://mailslurper
