version: v0.13.0

dsn: memory

serve:
  admin:
    port: 4434
  public:
    base_url: http://identity.127.0.0.1.sslip.io/kratos/
    port: 4433

selfservice:
  default_browser_return_url: http://auth.127.0.0.1.sslip.io/

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: http://auth.127.0.0.1.sslip.io/error

    settings:
      ui_url: http://auth.127.0.0.1.sslip.io/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://auth.127.0.0.1.sslip.io/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://auth.127.0.0.1.sslip.io/verification
      use: code
      after:
        default_browser_return_url: http://auth.127.0.0.1.sslip.io/

    logout:
      after:
        default_browser_return_url: http://auth.127.0.0.1.sslip.io/login

    login:
      ui_url: http://auth.127.0.0.1.sslip.io/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://auth.127.0.0.1.sslip.io/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: info
  format: json
  leak_sensitive_values: false

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

cookies:
  domain: 127.0.0.1.sslip.io
  same_site: Lax

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://mailslurper
