---
# Source: cert-manager-trust/templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-trust
  labels:
    app.kubernetes.io/name: cert-manager-trust
    helm.sh/chart: cert-manager-trust-v0.2.1
    app.kubernetes.io/instance: cert-manager-trust
    app.kubernetes.io/version: "v0.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  dnsNames:
    - "cert-manager-trust.cert-manager.svc"
  secretName: cert-manager-trust-tls
  revisionHistoryLimit: 1
  issuerRef:
    name: cert-manager-trust
---
# Source: cert-manager-trust/templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-trust
  labels:
    app.kubernetes.io/name: cert-manager-trust
    helm.sh/chart: cert-manager-trust-v0.2.1
    app.kubernetes.io/instance: cert-manager-trust
    app.kubernetes.io/version: "v0.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selfSigned: {}
