---
# Source: cert-manager-trust/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: cert-manager-trust
    helm.sh/chart: cert-manager-trust-v0.2.1
    app.kubernetes.io/instance: cert-manager-trust
    app.kubernetes.io/version: "v0.2.0"
    app.kubernetes.io/managed-by: Helm
  name: cert-manager-trust
rules:
  - apiGroups:
      - "trust.cert-manager.io"
    resources:
      - "bundles"
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - "trust.cert-manager.io"
    resources:
      - "bundles/status"
    verbs: ["update"]

  - apiGroups:
      - ""
    resources:
      - "configmaps"
    verbs: ["get", "list", "create", "update", "watch", "delete"]
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs: ["get", "list", "watch"]

  - apiGroups:
      - ""
    resources:
      - "events"
    verbs: ["create", "patch"]
