---
# Source: cert-manager-trust/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-trust
  labels:
    app.kubernetes.io/name: cert-manager-trust
    helm.sh/chart: cert-manager-trust-v0.2.1
    app.kubernetes.io/instance: cert-manager-trust
    app.kubernetes.io/version: "v0.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-trust
  template:
    metadata:
      labels:
        app: cert-manager-trust
    spec:
      serviceAccountName: cert-manager-trust
      containers:
        - name: cert-manager-trust
          image: "quay.io/jetstack/cert-manager-trust:v0.2.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6443
            - containerPort: 9402
          readinessProbe:
            httpGet:
              port: 6060
              path: /readyz
            initialDelaySeconds: 3
            periodSeconds: 7
          command: ["cert-manager-trust"]
          args:
            - "--log-level=1"
            - "--metrics-port=9402"
            - "--readiness-probe-port=6060"
            - "--readiness-probe-path=/readyz"
              # trust
            - "--trust-namespace=cert-manager"
              # webhook
            - "--webhook-host=0.0.0.0"
            - "--webhook-port=6443"
            - "--webhook-certificate-dir=/tls"
          volumeMounts:
            - mountPath: /tls
              name: tls
              readOnly: true
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: tls
          secret:
            defaultMode: 420
            secretName: cert-manager-trust-tls
