apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - custom-resource-definition.yaml
  - deployment.yaml
  - role-binding.yaml
  - role.yaml
  - service-account.yaml
  - webhook.yaml
