---
# Source: cert-manager-trust/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-trust
  labels:
    app.kubernetes.io/name: cert-manager-trust
    helm.sh/chart: cert-manager-trust-v0.2.1
    app.kubernetes.io/instance: cert-manager-trust
    app.kubernetes.io/version: "v0.2.0"
    app.kubernetes.io/managed-by: Helm
