---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apisix
spec:
  dependsOn:
    - name: linkerd
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: kube-apisix-linkerd-ory-kustomize
  path: ./infrastructure/apisix
