---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oathkeeper
  labels:
    app.kubernetes.io/name: oathkeeper
    app.kubernetes.io/instance: oathkeeper
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: oathkeeper
      app.kubernetes.io/instance: oathkeeper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oathkeeper
        app.kubernetes.io/instance: oathkeeper
      annotations:
        linkerd.io/inject: enabled
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: oathkeeper
        vault.hashicorp.com/agent-inject-secret-jwks.json: kv/data/applications/ory/oathkeeper/jwks
        vault.hashicorp.com/agent-inject-template-jwks.json: |
          {{- with secret "kv/data/applications/ory/oathkeeper/jwks" -}}
            {
              "keys": [
                {{ .Data.data | toUnescapedJSON }}
              ]
            }
          {{- end }}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: oathkeeper
      containers:
        - name: oathkeeper
          image: "oryd/oathkeeper:v0.40.6"
          imagePullPolicy: IfNotPresent
          command:
            - "oathkeeper"
          args:
            - "serve"
            - "--config"
            - "/etc/config/oathkeeper.yaml"
          volumeMounts:
            - name: oathkeeper-config-volume
              mountPath: /etc/config
              readOnly: true
            - name: oathkeeper-rules-volume
              mountPath: /etc/rules
              readOnly: true
          ports:
            - name: http-api
              containerPort: 4456
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/alive
              port: http-api
              httpHeaders:
                - name: Host
                  value: "127.0.0.1"
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/alive
              port: http-api
              httpHeaders:
                - name: Host
                  value: "127.0.0.1"
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health/alive
              port: http-api
              httpHeaders:
                - name: Host
                  value: "127.0.0.1"
            failureThreshold: 60
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seLinuxOptions:
              level: s0:c123,c456
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: oathkeeper-config-volume
          configMap:
            name: oathkeeper-config
        - name: oathkeeper-rules-volume
          configMap:
            name: oathkeeper-rules
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups: []
        sysctls: []
