apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: http-dump

resources:
  - manifests/apisix/routes.yaml
  - manifests/oathkeeper/rules.yaml
  - manifests/deployment.yaml
  - manifests/namespace.yaml
  - manifests/service.yaml
