---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: protected
spec:
  upstream:
    url: "http://no-where"
  match:
    url: http://http-dump.127.0.0.1.sslip.io/protected
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
