apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ory

resources:
  - manifests/apisix/route.yaml
  - manifests/courier/rbac.yaml
  - manifests/courier/service.yaml
  - manifests/courier/statefulset.yaml
  - manifests/migration/job.yaml
  - manifests/migration/rbac.yaml
  - manifests/deployment.yaml
  - manifests/rbac.yaml
  - manifests/services.yaml

configMapGenerator:
  - name: kratos-config
    files:
      - config/kratos.yaml
      - config/identity.schema.json
